import NavBar from '@/components/nav-bar'
import './globals.css'
import { getCurrentUser } from '@/lib/session'
import { Inter as FontSans } from 'next/font/google'

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-inter",
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const user = await getCurrentUser();

  return (
    <html lang="en" className={fontSans.variable + " font-sans antialiased bg-zinc-800"} data-theme="dark">
      <body className=''>
        <NavBar user={user} />
        {children}
      </body>
    </html>
  )
}
